require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported

prepare_react_native_project!

# Firebase configuration
$RNFirebaseDisableSPM = true
$RNFirebaseAsStaticFramework = true

# Use React Native's source core instead of prebuilt RN core
ENV['RCT_USE_PREBUILT_RNCORE'] = '0'

pod 'GoogleUtilities', :modular_headers => true
pod 'FirebaseCoreInternal', :modular_headers => true

target 'MyNavigationApp' do

  config = use_native_modules!
  pod 'SDWebImage', :modular_headers => true

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(installer)

    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
  end

end